flowchart TD
    subgraph Server["🖥️ Servidor"]
        C -->|Consulta DAOUser | D[Server DAO User <br> getUserByUsername]
        D -->|Respon Objecte User if exists| C
    end
    
    subgraph Client["🌐 Client"]
        A[<b>Client View</b> <br> Input username] -->|Envia dades username| B[Client DAO User<br> getUserByUsername]
        B -->|Petición HTTP  GET | C[<b>Servidor</b> <br> Webservice]
        B -->|Dades processades| F[<b>Client View</b> <br> Show Info User if exists]
        C -->|Reposta HTTP Json | B
    end       

    classDef client fill:#D6EAF8,stroke:#333,stroke-width:2px;
    classDef server fill:#F9EBEA,stroke:#333,stroke-width:2px;

    class A client;
    class B client;
    class F client;
    class C server;
    class D server;